### ISSUE TITLE
Cambiar paleta de colores.

### ISSUE THREAD

**Issue by pin3da** [pereira-tech-talks/pereiratechtalks.com#1]
Debe estar acorde con el logo.

**Comment by szter** [comment]
Me gustaria ayudar

**Comment by pin3da** [comment]
Hola @szter, muchas gracias por el interes!

La idea es tomar los logos que estan en https://github.com/pereira-tech-talks/art y cambiar el css para que quede mas acorde con estos colores.

Cualquier duda o ayuda que necesites vamos a estar pendientes (:

**Comment by santiaguf** [comment]
Ahora que estamos migrando el sitio de Ghost a Astro podemos revisar eso.

**Comment by arodrigueze0215** [comment]
Nos es mala idea. Incluso podríamos aprovechar para hacer un cambio de imagen, cambio de logo y la paleta de colores.

**Comment by santiaguf** [comment]
@szt-r, @arodrigueze0215 voy a cerrar el issue, si desean colaborar con el nuevo sitio web, pueden clonar el repo y/o ver los últimos cambios [aquí](https://v2.pereiratechtalks.com/).
