### ISSUE TITLE
Inclusión de biografías para los ponentes y adición de un nuevo speaker en la sección de "Speakers"

### ISSUE THREAD

**Issue by josefdc** [pereira-tech-talks/pereiratechtalks.com#126]
![image](https://github.com/user-attachments/assets/8af03d1c-5bd3-4e3f-b5ee-ac69b3088458)

En la sección de Speakers de nuestra página actualmente no se incluyen las biografías de los ponentes. Agregar una breve descripción de cada uno podría atraer más público y facilitar la obtención de patrocinios, ya que los asistentes y sponsors podrían conocer mejor a los expertos que estarán presentando.

**Tareas a realizar:**

1. **Adjuntar Biografías de Ponentes Existentes**: Por favor, adjuntemos las biografías de Vanessa Aristizabal y Karolina Ladino, cuya información se encuentra ya en nuestro drive.

2. **Inclusión de José Jaramillo como Ponente**: Necesitamos añadir a José Jaramillo a nuestra lista de speakers. Por favor, incluyamos su foto y biografía que, al igual que con los otros ponentes, se encuentra disponible en nuestro drive.

Gracias por su atención a esta solicitud 🫶

**Comment by stivencardona** [comment]
Seccion agregada
