### ISSUE TITLE
[Meetups] Almacenamiento en el Blog

### ISSUE THREAD

**Issue by arendondiosa** [pereira-tech-talks/pereiratechtalks.com#63]
Traer la información the meetup.com sobre eventos anteriores y almacenarla estáticamente como entradas del blog. El beneficio es que se alimenta los datos RSS y la idea a futuro es crear la conexión RSS - Telegram u otros 

- La vista `/meetups` renderiza los últimos eventos
  - Almacenar todos los eventos existentes con un tag que los diferencie para poder filtrar
  - Luego de almacenados, solo renderizar los últimos eventos en la vista para que el llamado sea ligero cuando se despliegue
- El evento próximo más cercano se debe seguir mostrando y apunta a la vista de Meetup.com para la inscripción
  - A su vez, crear la entrada en el blog
- Diseñar un workflow automatico para que la web se despliegue y refresque los eventos ya que en cada despliegue se consulta la API de meetup.com

**Comment by xergioalexpro** [comment]
@arendondiosa no he visto como implementaste esta parte, pero actualmente los eventos ya se renderizan estáticos cierto? lo que quieres es que simplemente ocurra un redespliegue cada X tiempo de forma automática para que renderice los últimos?

**Comment by arendondiosa** [comment]
@xergioalexpro correcto. Cuando hace build sólo se construyen estáticos con lo que esté en Meetup en ese momento.

**Comment by xergioalexpro** [comment]
Ya vi, listo yo puedo ayudar con este workflow
